import "~/styles/globals.css";


import { Karla } from "next/font/google";

//import { TRPCReactProvider } from "~/trpc/react";
import Appbar from "./_components/appbar";
import Header from "./_components/header";
import PageWrapper from "./_components/pagewrapper";
import SearchBox from './_components/searchBox';
import Footer from './_components/footer';

const karla = Karla({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body className={`font-sans ${karla.variable}`}>
        <div className="flex flex-col min-h-screen">
            <Appbar />
            <Header />
            <div className="flex-grow">
                <SearchBox />
                <PageWrapper>{children}</PageWrapper>
            </div>
            <Footer />
        </div>
        </body>
        </html>
    );
}

